#!/usr/bin/env bash
#
# Install DeepSeek Harness (`dsh`) from the committed pnpm lockfile.
#
# The lockfile pins the exact top-level version AND carries an integrity hash
# for every transitive package, so `--frozen-lockfile` is what makes the Node
# dependency graph reproducible.
#
# Expects the lock directory at /tmp/deepseek-harness (package.json +
# pnpm-lock.yaml), both copied in by the Dockerfile build stage.
#
# No wrapper script: `dsh` is the pnpm-generated bin shim for the package's own
# `bin` entry. Earlier releases needed an `--expose-internals` workaround for an
# upstream HMR-loader bug; 0.1.5-rc.1 no longer imports Node internals, and the
# `dsh --version` check below is what proves the shim is actually executable.
#
set -euo pipefail

DSH_VERSION="${DSH_VERSION:-0.1.5-rc.1}"
install_root=/opt/deepseek-harness
lock_root=/tmp/deepseek-harness

locked_version="$(sed -n '/^[[:space:]]*specifier:/ { s/.*specifier:[[:space:]]*//; s/[[:space:]]*$//; p; q; }' "$lock_root/pnpm-lock.yaml")"
[[ "$locked_version" == "$DSH_VERSION" ]] || {
  echo "ERROR: DeepSeek Harness lockfile has $locked_version, expected $DSH_VERSION" >&2
  exit 1
}

mkdir -p "$install_root"
cp "$lock_root/package.json" "$lock_root/pnpm-lock.yaml" "$install_root/"

corepack enable
corepack prepare pnpm@11.7.0 --activate
pnpm --dir "$install_root" install --prod --frozen-lockfile --ignore-scripts

# Verify the installed tree is really the pinned version before we trust the shim.
installed_version="$(node -p "require('$install_root/node_modules/@deepseek-ai/dsh/package.json').version")"
[[ "$installed_version" == "$DSH_VERSION" ]] || {
  echo "ERROR: installed dsh $installed_version, expected $DSH_VERSION" >&2
  exit 1
}

# Put `dsh` on PATH via a generated wrapper rather than pnpm's
# node_modules/.bin shim. The shim computes its target from its own location, so
# exposing it through a symlink in /usr/local/bin makes it look for the package
# under /usr/local/.pnpm/... and fail with "Cannot find module
# '/usr/local/.pnpm/@deepseek-ai+dsh.../lib/bin.js'".
#
# The entry point is read from the package's own package.json `bin` field (which
# is a string or a map depending on the publisher), so this stays correct if
# upstream renames the file.
entry="$(node -e '
  const fs = require("fs");
  const root = process.argv[1];
  const pkg = JSON.parse(fs.readFileSync(root + "/node_modules/@deepseek-ai/dsh/package.json", "utf8"));
  const bin = pkg.bin;
  const rel = typeof bin === "string" ? bin : (bin && bin.dsh);
  if (!rel) { console.error("no dsh bin entry in package.json"); process.exit(1); }
  process.stdout.write(root + "/node_modules/@deepseek-ai/dsh/" + rel);
' "$install_root")"

[[ -f "$entry" ]] || { echo "ERROR: dsh entry point not found at $entry" >&2; exit 1; }

cat > /usr/local/bin/dsh <<EOF
#!/bin/sh
# Generated by install-deepseek-harness.sh; invokes the pinned DeepSeek Harness
# entry point directly. Do not hand-edit: rebuild the image instead.
exec node "$entry" "\$@"
EOF
chmod 0755 /usr/local/bin/dsh

dsh --version | grep -Fx "$DSH_VERSION" >/dev/null
dsh --profile headless --dump-default-config >/dev/null

echo ">> install-deepseek-harness.sh: dsh $DSH_VERSION installed and verified"
